# Generated by Django 3.1.3 on 2021-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frd_name', models.CharField(max_length=20)),
                ('DOB', models.DateField(max_length=20)),
                ('frd_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
