# Generated by Django 3.1.3 on 2021-02-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(max_length=20)),
                ('proUserName', models.CharField(max_length=20, unique=True)),
                ('proEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rango.userprofile'),
        ),
    ]
