# Generated by Django 3.1.3 on 2021-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210209_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='owner',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
